=== Louis-Davies/food-truck-system/team1-app/resources/dtd/compositeFooditem.dtd
<!ENTITY version "V0.01 (C) Rosemary">
<!ELEMENT cfooditems (description, (cfooditem*))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT cfooditem (code, name, calorieCount, components, ingredientCounts, recipeNotes, salePrice)>
<!ATTLIST cfooditem
        unit (g|ml|count|unknown) #REQUIRED
        isVegetarian (yes|no|optional) "no"
        isVegan (yes|no|optional) "no"
        isGlutenFree (yes|no|optional) "optional"
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT calorieCount (#PCDATA)>
<!ELEMENT components (#PCDATA)>
<!ELEMENT ingredientCounts (#PCDATA)>
<!ELEMENT recipeNotes (#PCDATA)>
<!ELEMENT salePrice (#PCDATA)>

=== Louis-Davies/food-truck-system/team1-app/resources/data/CompositeFoodItem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE cfooditems SYSTEM "compositeFooditem.dtd">
<cfooditems>
    <description>Food sold by our food truck</description>
    <cfooditem unit="g">
        <code>BeefBurg</code>
        <name>Hamburger</name>
        <calorieCount>295</calorieCount>
        <components></components>
        <ingredientCounts></ingredientCounts>
        <recipeNotes></recipeNotes>
        <salePrice></salePrice>
    </cfooditem>
    <cfooditem unit="g">
        <code>CheeseBurg</code>
        <name>Cheeseburger</name>
        <calorieCount>303</calorieCount>
        <components></components>
        <ingredientCounts></ingredientCounts>
        <recipeNotes></recipeNotes>
        <salePrice></salePrice>
    </cfooditem>
    <cfooditem unit="g" isVegetarian="yes">
        <code>TofuBurg</code>
        <name>Tofu Burger</name>
        <calorieCount>168.4</calorieCount>
        <components></components>
        <ingredientCounts></ingredientCounts>
        <recipeNotes></recipeNotes>
        <salePrice></salePrice>
    </cfooditem>
    <cfooditem unit="ml" isVegan="yes">
        <code>AppleSoda</code>
        <name>Sparkling Apple Juice</name>
        <calorieCount>87</calorieCount>
        <components></components>
        <ingredientCounts></ingredientCounts>
        <recipeNotes></recipeNotes>
        <salePrice></salePrice>
    </cfooditem>
</cfooditems>
