=== Louis-Davies/food-truck-system/team1-app/resources/dtd/SuppliedFoodItem.dtd
<!ENTITY version "V0.01 (C) Rosemary">
<!ELEMENT sfooditems (description, (sfooditem*))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT sfooditem (code, name)>
<!ATTLIST sfooditem
        unit (g|ml|count|unknown) #REQUIRED
        isVegetarian (yes|no|unknown) "no"
        isVegan (yes|no|unknown) "no"
        isGlutenFree (yes|no|unknown) "unknown"
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT calorieCount (#PCDATA)>
<!ELEMENT suppliers (#PCDATA)>

=== Louis-Davies/food-truck-system/team1-app/resources/data/SuppliedFoodItem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sfooditems SYSTEM "SuppliedFoodItem.dtd">
<sfooditems>
    <description>Our sfooditems in no particular order (incomplete).</description>
    <sfooditem unit="ml">
        <code>Salt</code>
        <name>Table salt</name>
    </sfooditem>
    <sfooditem unit="count" isGlutenFree="no">
        <code>BBun</code>
        <name>Hamburger bun</name>
    </sfooditem>
    <sfooditem unit="count" isVegan="no" isVegetarian="no">
        <code>BPat</code>
        <name>Beef patty</name>
    </sfooditem>
    <sfooditem unit="g" isVegan="yes">
        <code>Onion</code>
        <name>Diced onion</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>TSauce</code>
        <name>Tomato sauce</name>
    </sfooditem>
    <sfooditem unit="count" isGlutenFree="yes">
        <code>Beetroot</code>
        <name>Beetroot slice</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Lettuce</code>
        <name>Sliced Iceberg lettuce</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Mayo</code>
        <name>Eater plain Mayonnaise</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Chicken</code>
        <name>Chicken breast, diced</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Rice</code>
        <name>Long grain rice</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Soy</code>
        <name>Soy sauce, dark</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Oil</code>
        <name>Canola oil</name>
    </sfooditem>
    <sfooditem unit="count">
        <code>LemCan</code>
        <name>Lemonade, 300ml Can</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>OlOil</code>
        <name>Olive oil, extra virgin</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Bacon</code>
        <name>Bacon, shoulder</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Garlic</code>
        <name>Garlic, sliced</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Brandy</code>
        <name>Brandy, Courvoisier, 1l</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>RedWine</code>
        <name>Red wine, 1l cask</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>CStock</code>
        <name>Chicken stock</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Herbs</code>
        <name>Mixed herbs, dried</name>
    </sfooditem>
    <sfooditem unit="count">
        <code>Bay</code>
        <name>Bay leaf, dried</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Shrooms</code>
        <name>Button mushrooms, sliced</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Flour</code>
        <name>Flour, plain</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Vodka</code>
        <name>Vodka, Ivan's special brew, 1l</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Cassis</code>
        <name>Torlesse Cassis, 750ml</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>Cream</code>
        <name>Cream</name>
    </sfooditem>
    <sfooditem unit="g">
        <code>Choc</code>
        <name>Smith's Drinking chocolate</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>RegMilk</code>
        <name>Milk, homogenised</name>
    </sfooditem>
    <sfooditem unit="ml">
        <code>TrimMilk</code>
        <name>Trim milk</name>
    </sfooditem>
    <sfooditem unit="count">
        <code>Cheese</code>
        <name>Cheddar cheese slice</name>
    </sfooditem>
</sfooditems>
