=== Louis-Davies/food-truck-system/team1-app/src/test/resources/dtd/fooditems.dtd
<!ENTITY version "V0.01 (C) Rosemary">
<!ELEMENT fooditems (description, (fooditem*))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT fooditem (code, name, caloriesPerUnit)>
<!ATTLIST fooditem
        unit (g|ml|count|unknown) #REQUIRED
        isVegetarian (yes|no|optional) #IMPLIED
        isVegan (yes|no|optional) #IMPLIED
        isGlutenFree (yes|no|optional) #IMPLIED
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT caloriesPerUnit (#PCDATA)>

=== Louis-Davies/food-truck-system/team1-app/src/test/resources/xml/TESTXML2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fooditems SYSTEM "fooditems.dtd">
<fooditems>
    <description>Food sold by our food truck - file 2</description>
    <fooditem unit="count">
        <code>BANANA</code>
        <name>Banana</name>
        <cost>NZD 1.00</cost>
        <caloriesPerUnit>100</caloriesPerUnit>
    </fooditem>
    <fooditem unit="count">
        <code>APPLEPIE</code>
        <name>Apple Pie</name>
        <cost>NZD 21.00</cost>
        <caloriesPerUnit>200</caloriesPerUnit>
    </fooditem>
    <fooditem unit="g" isVegetarian="yes">
        <code>TOFUBURG</code>
        <name>Tofu Burger</name>
        <cost>NZD 50.00</cost>
        <caloriesPerUnit>268.4</caloriesPerUnit>
    </fooditem>
    <fooditem unit="ml" isVegan="yes" isGlutenFree="yes">
        <code>WATER</code>
        <name>Glass of water</name>
        <cost>NZD 200.00</cost>
        <caloriesPerUnit>0</caloriesPerUnit>
    </fooditem>

</fooditems>
