=== Louis-Davies/food-truck-system/team1-app/src/main/resources/dtd/fooditems.dtd
<!ENTITY version "V0.01 (C) Rosemary">
<!ELEMENT fooditems (description, (fooditem*))>
<!ELEMENT description (#PCDATA)>
<!ELEMENT fooditem (code, name, cost, caloriesPerUnit, recipe)>
<!ATTLIST fooditem
        unit (g|ml|count|unknown) #REQUIRED
        isVegetarian (yes|no) #IMPLIED
        isVegan (yes|no) #IMPLIED
        isGlutenFree (yes|no) #IMPLIED
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT caloriesPerUnit (#PCDATA)>
<!ELEMENT recipe ((ingredient*), (addableIngredient*))>
<!ELEMENT ingredient (code, name, cost, caloriesPerUnit, amount)>
<!ATTLIST ingredient
        unit (g|ml|count|unknown) #REQUIRED
        isVegetarian (yes|no) #IMPLIED
        isVegan (yes|no) #IMPLIED
        isGlutenFree (yes|no) #IMPLIED
>
<!ELEMENT addableIngredient (code, name, cost, caloriesPerUnit, amount)>
<!ATTLIST addableIngredient
        unit (g|ml|count|unknown) #REQUIRED
        isVegetarian (yes|no) #IMPLIED
        isVegan (yes|no) #IMPLIED
        isGlutenFree (yes|no) #IMPLIED
>
<!ELEMENT amount (#PCDATA)>

=== Louis-Davies/food-truck-system/team1-app/src/test/resources/xml/TESTXML1WITHRECIPE.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fooditems SYSTEM "fooditems.dtd">
<fooditems>
    <description>Food sold by our food truck</description>
    <fooditem unit="g">
        <code>BEEFBURG</code>
        <name>Hamburger</name>
        <cost>NZD 21.00</cost>
        <caloriesPerUnit>295</caloriesPerUnit>
        <recipe>
            <ingredient unit="count">
                <code>BEEF</code>
                <name>Beef</name>
                <cost>NZD 0</cost>
                <caloriesPerUnit>250</caloriesPerUnit>
                <amount>1</amount>
            </ingredient>
            <ingredient unit="count">
                <code>BUN</code>
                <name>Bun</name>
                <cost>NZD 0</cost>
                <caloriesPerUnit>210</caloriesPerUnit>
                <amount>2</amount>
            </ingredient>
            <ingredient unit="count">
                <code>LETTUCE</code>
                <name>Lettuce</name>
                <cost>NZD 0</cost>
                <caloriesPerUnit>15</caloriesPerUnit>
                <amount>1</amount>
            </ingredient>
            <addableIngredient unit="count">
                <code>EGG</code>
                <name>Egg</name>
                <cost>NZD 0</cost>
                <caloriesPerUnit>155</caloriesPerUnit>
                <amount>1</amount>
            </addableIngredient>
        </recipe>
    </fooditem>
    <fooditem unit="g">
        <code>CHEESEBURG</code>
        <name>Cheeseburger</name>
        <cost>NZD 22.00</cost>
        <caloriesPerUnit>303</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
    <fooditem unit="g" isVegetarian="yes">
        <code>TOFUBURG</code>
        <name>Tofu Burger</name>
        <cost>NZD 50.00</cost>
        <caloriesPerUnit>168.4</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
    <fooditem unit="ml" isVegan="yes" isGlutenFree="yes">
        <code>APPLESODA</code>
        <name>Sparkling Apple</name>
        <cost>NZD 96.00</cost>
        <caloriesPerUnit>87</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
</fooditems>

=== Louis-Davies/food-truck-system/team1-app/resources/data/FoodItem3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fooditems SYSTEM "fooditems.dtd">
<fooditems>
    <description>Food sold by our food truck - file 2</description>
    <fooditem unit="count">
        <code>BANANA</code>
        <name>Banana</name>
        <cost>NZD 69.00</cost>
        <caloriesPerUnit>100</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
</fooditems>

=== Louis-Davies/food-truck-system/team1-app/resources/data/FoodItem2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE fooditems SYSTEM "fooditems.dtd">
<fooditems>
    <description>Food sold by our food truck - file 2</description>
    <fooditem unit="count">
        <code>BANANA</code>
        <name>Banana</name>
        <cost>NZD 1.00</cost>
        <caloriesPerUnit>100</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
    <fooditem unit="count">
        <code>APPLEPIE</code>
        <name>Apple Pie</name>
        <cost>NZD 21.00</cost>
        <caloriesPerUnit>200</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
    <fooditem unit="ml" isVegetarian="yes">
        <code>ORNGJCE</code>
        <name>Orange Juice</name>
        <cost>NZD 60.00</cost>
        <caloriesPerUnit>312.4</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
    <fooditem unit="ml" isVegan="yes" isGlutenFree="yes">
        <code>WATER</code>
        <name>Glass of water</name>
        <cost>NZD 200.00</cost>
        <caloriesPerUnit>0</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>
    <fooditem unit="ml" isVegan="yes" isGlutenFree="yes">
        <code>APPLESODA</code>
        <name>Sparkling Apple</name>
        <cost>NZD 120.00</cost>
        <caloriesPerUnit>10000</caloriesPerUnit>
        <recipe></recipe>
    </fooditem>

</fooditems>
