=== Louis-Davies/food-truck-system/team1-app/src/main/resources/dtd/menu.dtd
<!ENTITY version "V0.01 (C) Rosemary">
<!ELEMENT menu (name, description, (fooditem*))>
<!ATTLIST menu
    from CDATA #IMPLIED
    to CDATA #IMPLIED
>
<!ELEMENT description (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT fooditem (code)>
<!ELEMENT code (#PCDATA)>

-- <!ATTLIST name serves CDATA "1">
<!ELEMENT item (name)>
<!ATTLIST item
    unit (ml|g|count) #REQUIRED
    quantity CDATA #REQUIRED
> --

=== Louis-Davies/food-truck-system/team1-app/resources/data/SampleMenu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE menu SYSTEM "../dtd/menu.dtd">
<menu from="June" to="August">
    <name>Winter warmers</name>
    <description>Sample menu: Things we sell in cold weather</description>
    <fooditem>
        <code>burg</code>
    </fooditem>
    <fooditem>
        <code>chowder</code>
    </fooditem>
    <fooditem>
        <code>deep fried soup</code>
    </fooditem>
    <fooditem>
        <code>garlic bread</code>
    </fooditem>
    <fooditem>
        <code>cocktail</code>
    </fooditem>
    <fooditem>
        <code>hot choc</code>
    </fooditem>
</menu>
